# General settings
SQLALCHEMY_DATABASE_URI = 'postgresql:///indico'
SECRET_KEY = b'`\xa7\xf4;~^\x9c\xb1h\xbd\xfcw\xde\xfd\xc5\x8c\x91\x00u\xc5\xfc\xb3\xbaC*Y-W\xee\x05\xc2\x9f'
BASE_URL = 'http://127.0.0.1:8000'
CELERY_BROKER = 'redis://127.0.0.1:6379/0'
REDIS_CACHE_URL = 'redis://127.0.0.1:6379/1'
DEFAULT_TIMEZONE = 'Africa/Kampala'
DEFAULT_LOCALE = 'en_GB'
ENABLE_ROOMBOOKING = False
CACHE_DIR = '/home/collin/dev/indico/data/cache'
TEMP_DIR = '/home/collin/dev/indico/data/tmp'
LOG_DIR = '/home/collin/dev/indico/data/log'
STORAGE_BACKENDS = {'default': 'fs:/home/collin/dev/indico/data/archive'}
ATTACHMENT_STORAGE = 'default'

# Email settings
SMTP_SERVER = ('smtp.gmail.com', 587)
SMTP_USE_TLS = True
SMTP_LOGIN = 'collinslusiba@gmail.com'
SMTP_PASSWORD = 'ilbk hryw ajsk sugj'
SUPPORT_EMAIL = 'collinslusiba@gmail.com'
PUBLIC_SUPPORT_EMAIL = ''
NO_REPLY_EMAIL = 'noreply@gmail.com'

# Development options
DB_LOG = True
DEBUG = True
SMTP_USE_CELERY = False
